## config.toml
## Example replication-manager configuration file

## change the service file  in /etc/systemd/system/replication-manager.service to looks like :
## replication-manager-osc  --config=./etc/config.toml.sample  --cluster=Cluster01,Cluster_Test_2_Nodes monitor

[ClusterTestConsul]
title = "ClusterTestConsul"

prov-orchestrator = "local"
db-servers-hosts = "127.0.0.1:3331,127.0.0.1:3332"
db-servers-prefered-master = "127.0.0.1:3331"
db-servers-credential = "root:mariadb"
db-servers-connect-timeout = 1
replication-credential = "root:mariadb"
registry-consul = true
