[galera]
title = "galera"
db-servers-hosts = "db1,db2,db3"
db-servers-prefered-master = "db1"
db-servers-connect-timeout = 1
# failover-mode = "automatic"
autorejoin-mysqldump = true
force-slave-failover-readonly-state = true
prov-db-docker-img = "mariadb:10.5.18"
#prov-db-docker-img = "quay.io/mariadb-foundation/mariadb-devel:10.5"
prov-serialized = true
prov-db-tags = "docker,smallredolog,innodb,noquerycache,threadpool,logslow,wsrep,nosplitpath"
prov-db-disk-size = "1G"
prov-proxy-disk-size ="1G"
replication-multi-master-wsrep = true
replication-multi-master-wsrep-sst-method = "rsync_wan"
#replication-multi-master-wsrep-sst-method = "rsync"
#replication-multi-master-wsrep-sst-method = "mariabackup"
# mariadbbackup failed cause can not rm mount point under .system
haproxy=true
haproxy-servers = "haproxy1"

proxysql=true
proxysql-servers = "proxysql1"
proxysql-user ="external"
proxysql-bootstrap= true
proxysql-copy-grants = true
