[grouprep]
title = "grouprep"
db-servers-hosts = "db1,db2,db3"
db-servers-prefered-master = "db1"
db-servers-connect-timeout = 1
# failover-mode = "automatic"
autorejoin-mysqldump = true
force-slave-failover-readonly-state = true
prov-db-docker-img = "mysql:latest"
prov-db-tags = "docker,smallredolog,innodb,noquerycache,threadpool,logslow,grouprep,nosplitpath"
prov-db-disk-size = "1G"
prov-proxy-disk-size ="1G"
replication-multi-master-grouprep = true
haproxy=true
haproxy-servers = "haproxy1"
