[Default]

include = "./etc/local/masterslave/proxysql"
prov-orchestrator = "onpremise"
onpremise-ssh = true
onpremise-ssh-credential = "emma:"
scheduler-jobs-ssh = true
monitoring-address = "192.168.1.136"
monitoring-scheduler = true
scheduler-db-servers-logs = true
scheduler-db-servers-logs-cron = "0 * * * * *"
scheduler-db-servers-physical-backup = false
backup-physical-type = "mariabackup"
scheduler-db-servers-optimize = false
scheduler-db-servers-logical-backup = false
scheduler-db-servers-logs-table-rotate = false

#mariadb
prov-db-binary-basedir= "/usr/sbin"
prov-db-client-basedir= "/usr/bin"
backup-mysqlclient-path ="/usr/bin/mysql"
backup-mysqlbinlog-path = "/usr/bin/mysqlbinlog"
backup-mysqldump-options = "--hex-blob --single-transaction --verbose --all-databases --add-drop-database"

#monitoring-save-config = true
#monitoring-key-path = ".replication-manager.key"

monitoring-sharedir="./share"
monitoring-datadir="/home/emma/repdata"
http-root="./share/dashboard"

## Timeout in seconds between consecutive monitoring

monitoring-ticker = 2

#########
## LOG ##
#########

log-file = "/var/log/replication-manager.log"
log-heartbeat = false


##########
## HTTP ##
##########

http-server = true
http-bind-address = "0.0.0.0"
http-port = "10001"
http-auth = false
http-session-lifetime =   3600
http-bootstrap-button = false
http-refresh-interval = 4000

#########
## API ##
#########

api-credentials = "admin:repman"
api-port = "10005"


